import {useCallback,useState} from 'react';
import api from '../api';
import {useRefresh} from '../hooks';
import {useAuth} from '../context';
import {Users,Building2,FolderKanban,ListTodo,Clock,CheckCircle2,AlertTriangle,ArrowUpRight,XCircle,Plane,TimerReset,UserCheck,ClipboardCheck,ShieldAlert} from 'lucide-react';
import {Badge,Skeleton,Empty} from '../components/UI';
import {Link} from 'react-router-dom';

const dailyTone={todo:'muted','in-progress':'blue',submitted:'purple',approved:'green',rework:'orange'};

export default function Dashboard(){
  const {user}=useAuth();
  const [data,setData]=useState(null),[insights,setInsights]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=useCallback(()=>{
    setLoading(true);setError('');
    const calls=[api.get('/dashboard')];
    if(user.role!=='employee')calls.push(api.get('/manager-insights'));
    return Promise.all(calls).then(([dashboard,manager])=>{setData(dashboard.data);setInsights(manager?.data||null)}).catch(e=>{
      setError(e.response?.data?.message||'Unable to load dashboard');
      setData(null);setInsights(null);
    }).finally(()=>setLoading(false));
  },[user.role]);
  useRefresh(load);
  if(loading)return <Skeleton/>;
  if(error)return <Empty title="Unable to load dashboard" text={error}/>;
  const t=data?.stats.tasks||{};
  const today=data?.today||{};
  const cards=user.role==='employee'?[[t.total||0,'My Daily Tasks',ListTodo,'/daily-work'],[t['in-progress']||0,'In Progress',Clock,'/daily-work'],[t.pending||0,'Pending',ArrowUpRight,'/daily-work'],[t.approved||0,'Approved',CheckCircle2,'/daily-work']]:[[data.stats.users,user.role==='admin'?'My Team':'People',Users,'/users'],[data.stats.departments,'Departments',Building2,'/departments'],[data.stats.projects,'Projects',FolderKanban,'/projects'],[t.total||0,'Total Daily Tasks',ListTodo,'/daily-work']];
  return <>
    <div className="welcome"><div><p className="eyebrow">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</p><h1>Good to see you, {user.name.split(' ')[0]}</h1><p>{user.role==='employee'?`Employee ID: ${user.employeeCode||'Not assigned'}`:'Here is what is happening across your workspace today.'}</p></div><Link className="btn primary" to="/tasks">Open task board <ArrowUpRight size={17}/></Link></div>
    {user.role==='admin'&&!user.department&&<div className="notice warning"><Building2/><div><b>Create your department first</b><p>Your employees, projects, tasks and daily updates will live inside your department.</p><Link className="btn primary" to="/departments">Create department <ArrowUpRight size={16}/></Link></div></div>}
    <div className="grid cols-4">{cards.map(([v,l,I,to],i)=><Link className="stat card stat-link" to={to} key={l}><div className={'stat-icon i'+i}><I/></div><div><span>{l}</span><strong>{v}</strong><small>Live data</small></div></Link>)}</div>
    <section className="command-center card"><div className="section-head"><div><h3>Today Command Center</h3><p>Fast operational signals for the current day</p></div>{user.role!=='employee'&&<Link to="/approvals">Open approvals</Link>}</div><div className="command-grid"><Link to="/daily-work" className="command-item"><ListTodo/><span>Due today</span><b>{today.dueToday||0}</b></Link><Link to="/daily-work" className="command-item danger"><AlertTriangle/><span>Overdue</span><b>{today.overdue||0}</b></Link><Link to={user.role==='employee'?'/leave':'/approvals'} className="command-item"><Plane/><span>Pending leave</span><b>{today.pendingLeaves||0}</b></Link><Link to="/attendance" className="command-item good"><CheckCircle2/><span>Present</span><b>{today.present||0}</b></Link><Link to="/attendance" className="command-item warn"><TimerReset/><span>Late</span><b>{today.late||0}</b></Link><Link to="/daily-work" className="command-item"><Clock/><span>Daily submitted</span><b>{today.dailySubmitted||0}</b></Link></div></section>
    {user.role!=='employee'&&insights&&<section className="team-control card"><div className="section-head"><div><h3>{user.role==='admin'?'My Team Control Room':'Workforce Control Room'}</h3><p>Manager-ready view of attendance, daily updates and task risk</p></div><Link to="/daily-work">Review daily work</Link></div><div className="team-metrics"><Link to="/users"><UserCheck/><span>Team size</span><b>{insights.summary.teamSize}</b></Link><Link to="/attendance"><CheckCircle2/><span>Checked in</span><b>{insights.summary.present+insights.summary.late}</b></Link><Link to="/daily-work"><ClipboardCheck/><span>Missing daily</span><b>{insights.summary.missingDaily}</b></Link><Link to="/tasks" className={insights.summary.overdue?'hot':''}><ShieldAlert/><span>Overdue</span><b>{insights.summary.overdue}</b></Link></div>{insights.alerts?.length>0&&<div className="insight-alerts">{insights.alerts.map(a=><Link to={a.link} className={'insight-alert '+a.tone} key={a.title}><AlertTriangle/><div><b>{a.title}</b><span>{a.message}</span></div><ArrowUpRight/></Link>)}</div>}<div className="team-table"><div className="team-table-head"><span>Employee</span><span>Attendance</span><span>Daily update</span><span>Open work</span><span>Signal</span></div>{insights.team?.length?insights.team.map(x=><Link to={`/users`} className={'team-table-row '+(x.risk?'risk':'')} key={x.employee._id}><div className="person"><div className="avatar">{x.employee.name?.[0]}</div><div><b>{x.employee.name}</b><span>{x.employee.designation||x.employee.department?.name||'Employee'}</span></div></div><Badge tone={x.attendance?.status==='late'?'orange':x.attendance?'green':'red'}>{x.attendance?.status||'no check-in'}</Badge><Badge tone={['submitted','approved'].includes(x.daily?.status)?'green':x.daily?.status==='rework'?'orange':'muted'}>{x.daily?.status||'pending'}</Badge><span><b>{x.taskCount}</b> open, <b>{x.overdue}</b> overdue</span><small>{x.signals?.length?x.signals.join(' | '):'On track'}</small></Link>):<Empty title="No team data" text="Assign employees to managers to see live team insights."/>}</div></section>}
    <div className="grid dashboard-grid"><section className="card"><div className="section-head"><div><h3>Recent daily work</h3><p>Latest activity on assigned daily tasks</p></div><Link to="/daily-work">View all</Link></div><div className="task-list">{data.recent?.length?data.recent.map(x=><div className="task-row" key={x._id}><div className="task-dot"/><div className="grow"><b>{x.title}</b><span>{x.employee?.name||'Employee'} · Due {x.dueTime||'—'} · {x.date}</span></div><Badge tone={dailyTone[x.status]}>{x.status.replace('-',' ')}</Badge><small>{x.progress||0}%</small></div>):<Empty title="No recent work" text="Recently assigned or updated daily tasks will appear here."/>}</div></section><section className="card"><div className="section-head"><div><h3>Daily task health</h3><p>Status distribution of tasks assigned via Daily Work</p></div></div><div className="health-list">{[['Approved',t.approved||0,'green'],['Submitted',t.submitted||0,'purple'],['In Progress',t['in-progress']||0,'blue'],['Pending',t.pending||0,'orange'],['Rework',t.rework||0,'red']].map(([l,v,c])=><div key={l}><span><i className={c}/>{l}</span><b>{v}</b></div>)}</div>{(t.overdue||0)>0&&<div className="alert"><AlertTriangle/><span><b>{t.overdue} daily task(s)</b> are overdue.</span></div>}</section></div>
  </>;
}