module.exports={
  apps:[
    {
      name:'taskflow-api',
      script:'src/index.js',
      cwd:__dirname,
      instances:1,
      exec_mode:'fork',
      env:{
        NODE_ENV:'production',
        PORT:5000
      }
    }
  ]
};
