import {Router} from 'express';import asyncHandler from 'express-async-handler';import bcrypt from 'bcryptjs';import multer from 'multer';import path from 'path';import fs from 'fs';import crypto from 'crypto';import mongoose from 'mongoose';import {Department,User,Project,Task,DailyTaskTemplate,DailyWork,Attendance,Leave,Notification,Activity,Setting,OtpToken,ResetToken} from './models.js';import {protect,allow,signToken,scopeFilter} from './auth.js';import {cleanUser,logActivity,notify,emitOps,teamEmployeeIds} from './helpers.js';import {sendOtpSms,normalizePhone} from './sms.js';import {validateBody,schemas} from './validation.js';import {uploadAttachment} from './uploader.js';
const uploadDir=path.resolve('uploads');fs.mkdirSync(uploadDir,{recursive:true});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
const parsePage=(req)=>({page:Math.max(1,Number(req.query.page)||1),limit:Math.min(100,Math.max(1,Number(req.query.limit)||20))});
const hist=(req,action,message,from='',to='')=>({actor:req.user._id,action,message,from:String(from||''),to:String(to||''),createdAt:new Date()});
const oid=id=>new mongoose.Types.ObjectId(id);
const safePhone=phone=>{try{return phone?normalizePhone(phone):null}catch{return null}};
const visibleTaskScope=async req=>req.user.role==='employee'?{assignedTo:req.user._id}:req.user.role==='admin'?{assignedTo:{$in:await teamEmployeeIds(req,User)}}:scopeFilter(req);
const managerEmployeeScope=async req=>req.user.role==='superadmin'?{}:{employee:{$in:await teamEmployeeIds(req,User)}};
export function createRouter(io){const r=Router();
r.post('/auth/login',asyncHandler(async(req,res)=>{const identifier=String(req.body.identifier||'').trim();const query=identifier.includes('@')?{email:identifier.toLowerCase()}:{phone:normalizePhone(identifier)};const user=await User.findOne(query).select('+password').populate('department','name code');if(!user||!await bcrypt.compare(req.body.password||'',user.password)){res.status(401);throw new Error('Invalid email/mobile number or password')}if(user.status!=='active'){res.status(403);throw new Error('Account is blocked')}user.lastLogin=new Date();await user.save();res.json({token:signToken(user),user:cleanUser(user)})}));
r.post('/auth/otp/send',validateBody(schemas.otpSend),asyncHandler(async(req,res)=>{const phone=normalizePhone(req.body.phone);const user=await User.findOne({phone,status:'active'});if(!user){res.status(404);throw new Error('No active account found for this mobile number')}const otp=String(Math.floor(100000+Math.random()*900000));await OtpToken.updateMany({phone,used:false},{$set:{used:true}});await OtpToken.create({phone,otpHash:crypto.createHash('sha256').update(otp).digest('hex'),expiresAt:new Date(Date.now()+5*60*1000)});await sendOtpSms(phone,otp);res.json({message:'OTP sent successfully'})}));
r.post('/auth/otp/verify',validateBody(schemas.otpVerify),asyncHandler(async(req,res)=>{const phone=normalizePhone(req.body.phone);const row=await OtpToken.findOne({phone,used:false,expiresAt:{$gt:new Date()}}).sort('-createdAt');if(!row){res.status(400);throw new Error('OTP expired or not found')}if(row.attempts>=5){res.status(429);throw new Error('Too many OTP attempts')}const hash=crypto.createHash('sha256').update(req.body.otp).digest('hex');if(hash!==row.otpHash){row.attempts+=1;await row.save();res.status(400);throw new Error('Invalid OTP')}row.used=true;await row.save();const user=await User.findOne({phone,status:'active'}).populate('department','name code');if(!user){res.status(404);throw new Error('No active account found for this mobile number')}user.lastLogin=new Date();await user.save();res.json({token:signToken(user),user:cleanUser(user)})}));
r.get('/auth/me',protect,asyncHandler(async(req,res)=>res.json(cleanUser(req.user))));
r.patch('/auth/profile',protect,validateBody(schemas.profile),asyncHandler(async(req,res)=>{for(const k of ['name','phone','designation','skills'])if(req.body[k]!==undefined)req.user[k]=req.body[k];await req.user.save();res.json(cleanUser(req.user))}));
r.patch('/auth/password',protect,validateBody(schemas.password),asyncHandler(async(req,res)=>{const u=await User.findById(req.user._id).select('+password');if(!await bcrypt.compare(req.body.currentPassword||'',u.password)){res.status(400);throw new Error('Current password is incorrect')}u.password=await bcrypt.hash(req.body.newPassword,12);await u.save();res.json({message:'Password changed'})}));
r.use(protect);
r.get('/dashboard',asyncHandler(async(req,res)=>{const scope=scopeFilter(req);const teamIds=await teamEmployeeIds(req,User);const taskScope=req.user.role==='employee'?{assignedTo:req.user._id}:req.user.role==='admin'?{assignedTo:{$in:teamIds}}:scope;const today=new Date().toISOString().slice(0,10);const start=new Date(today+'T00:00:00');const end=new Date(today+'T23:59:59');const attendanceScope=req.user.role==='employee'?{employee:req.user._id,date:today}:req.user.role==='superadmin'?{date:today}:{employee:{$in:teamIds},date:today};const leaveScope=req.user.role==='employee'?{employee:req.user._id,status:'pending'}:req.user.role==='superadmin'?{status:'pending'}:{employee:{$in:teamIds},status:'pending'};const dailyScope=req.user.role==='employee'?{employee:req.user._id,date:today}:req.user.role==='superadmin'?{date:today}:{employee:{$in:teamIds},date:today};const open={$nin:['completed','not-applicable']};const [users,departments,projects,tasks,recent,dueToday,overdue,pendingLeaves,present,late,dailySubmitted]=await Promise.all([req.user.role==='admin'?teamIds.length:User.countDocuments(req.user.role==='superadmin'?{}:scope),Department.countDocuments(req.user.role==='superadmin'?{}:{_id:req.user.department?._id}),Project.countDocuments(scope),Task.find(taskScope).populate('assignedTo','name avatar').populate('project','name').sort('-updatedAt').limit(6).lean(),Activity.find(req.user.role==='superadmin'?{}:{actor:req.user._id}).populate('actor','name').sort('-createdAt').limit(8).lean(),Task.countDocuments({...taskScope,dueDate:{$gte:start,$lte:end},status:open}),Task.countDocuments({...taskScope,dueDate:{$lt:start},status:open}),Leave.countDocuments(leaveScope),Attendance.countDocuments({...attendanceScope,status:{$in:['present','half-day']}}),Attendance.countDocuments({...attendanceScope,status:'late'}),DailyWork.countDocuments({...dailyScope,status:'submitted'})]);const taskCounts=await Task.aggregate([{$match:taskScope},{$group:{_id:'$status',count:{$sum:1}}}]);res.json({stats:{users,departments,projects,tasks:taskCounts.reduce((a,x)=>(a.total=(a.total||0)+x.count,a[x._id]=x.count,a),{})},today:{dueToday,overdue,pendingLeaves,present,late,dailySubmitted},recent,activity:recent})}));
r.get('/departments',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const own=[req.user.department,...(req.user.managedDepartments||[])].filter(Boolean);res.json(await Department.find(req.user.role==='superadmin'?{}:{$or:[{head:req.user._id},{_id:{$in:own}}]}).populate('head','name email').sort('name'))}));
r.post('/departments',allow('superadmin','admin'),validateBody(schemas.department),asyncHandler(async(req,res)=>{if(req.user.role==='admin')req.body.head=req.user._id;const x=await Department.create(req.body);if(req.user.role==='admin'){if(!req.user.department)req.user.department=x._id;req.user.managedDepartments=[...new Set([...(req.user.managedDepartments||[]).map(String),String(x._id)])];await req.user.save()}await logActivity(req,'create','Department',x._id,{name:x.name});emitOps(io,null,'department:updated',{id:x._id,action:'created'});emitOps(io,null,'dashboard:updated');res.status(201).json(await x.populate('head','name email'))}));
r.patch('/departments/:id',allow('superadmin','admin'),validateBody(schemas.department.partial()),asyncHandler(async(req,res)=>{const q=req.user.role==='superadmin'?{_id:req.params.id}:{_id:req.params.id,head:req.user._id};if(req.user.role==='admin'){delete req.body.head;delete req.body.status}const x=await Department.findOneAndUpdate(q,req.body,{new:true,runValidators:true});if(!x){res.status(404);throw new Error('Department not found')}await logActivity(req,'update','Department',x._id);emitOps(io,x._id,'department:updated',{id:x._id,action:'updated'});emitOps(io,null,'dashboard:updated');res.json(await x.populate('head','name email'))}));
r.delete('/departments/:id',allow('superadmin'),asyncHandler(async(req,res)=>{if(await User.exists({department:req.params.id})){res.status(409);throw new Error('Move users before deleting this department')}await Department.findByIdAndDelete(req.params.id);emitOps(io,req.params.id,'department:updated',{id:req.params.id,action:'deleted'});emitOps(io,null,'dashboard:updated');res.json({message:'Department deleted'})}));
r.get('/users',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const q=req.user.role==='admin'?{manager:req.user._id,role:'employee'}:{...scopeFilter(req)};if(req.query.role&&req.user.role!=='admin')q.role=req.query.role;if(req.query.search)q.$or=[{name:new RegExp(req.query.search,'i')},{email:new RegExp(req.query.search,'i')}];res.json(await User.find(q).populate('department','name code').populate('manager','name email').sort('-createdAt'))}));
r.get('/users/managers',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const q=req.user.role==='superadmin'?{role:'admin',status:'active'}:{_id:req.user._id};res.json(await User.find(q).select('name email department role').populate('department','name code').sort('name'))}));
r.get('/users/:id/scorecard',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const target=await User.findById(req.params.id).populate('department','name code').lean();if(!target){res.status(404);throw new Error('User not found')}if(req.user.role==='admin'&&String(target.manager)!==String(req.user._id)){res.status(403);throw new Error('Outside your team')}const taskMatch={assignedTo:oid(req.params.id)};const [taskCounts,approvedStats,attendanceCounts,leaveCounts,recentTasks]=await Promise.all([Task.aggregate([{$match:taskMatch},{$group:{_id:'$status',count:{$sum:1}}}]),Task.aggregate([{$match:{...taskMatch,status:'approved'}},{$group:{_id:null,completed:{$sum:1},avgRating:{$avg:'$privateEvaluation.rating'},points:{$sum:'$privateEvaluation.points'}}}]),Attendance.aggregate([{$match:{employee:oid(req.params.id)}},{$group:{_id:'$status',count:{$sum:1}}}]),Leave.aggregate([{$match:{employee:oid(req.params.id)}},{$group:{_id:'$status',count:{$sum:1}}}]),Task.find(taskMatch).select('title status priority progress dueDate updatedAt').sort('-updatedAt').limit(5).lean()]);const tasks=taskCounts.reduce((a,x)=>(a.total=(a.total||0)+x.count,a[x._id]=x.count,a),{});const attendance=attendanceCounts.reduce((a,x)=>(a.total=(a.total||0)+x.count,a[x._id]=x.count,a),{});const leaves=leaveCounts.reduce((a,x)=>(a.total=(a.total||0)+x.count,a[x._id]=x.count,a),{});const stats=approvedStats[0]||{completed:0,avgRating:0,points:0};const approvalRate=tasks.total?Math.round(((tasks.approved||0)/tasks.total)*100):0;const punctuality=attendance.total?Math.round((((attendance.present||0)+(attendance['half-day']||0)*.5)/attendance.total)*100):0;const score=Math.round((approvalRate*.55)+(punctuality*.25)+((Number(stats.avgRating||0)/5)*100*.2));res.json({user:target,tasks,attendance,leaves,completed:stats.completed||0,avgRating:Number(stats.avgRating||0).toFixed(1),points:stats.points||0,approvalRate,punctuality,score,recentTasks})}));
r.post('/users',allow('superadmin','admin'),validateBody(schemas.user),asyncHandler(async(req,res)=>{if(req.body.role==='superadmin'){res.status(409);throw new Error('Only one Super Admin is allowed in the organization')}if(req.user.role==='admin'){const allowed=[req.user.department,...(req.user.managedDepartments||[])].filter(Boolean).map(String);if(!allowed.length){res.status(400);throw new Error('Create a department before adding employees')}req.body.role='employee';if(!req.body.department)req.body.department=allowed[0];if(!allowed.includes(String(req.body.department))){res.status(403);throw new Error('Select one of your managed departments')}req.body.manager=req.user._id}if(req.user.role==='superadmin'&&req.body.role==='employee'){if(!req.body.manager){res.status(400);throw new Error('Select a reporting manager for employee')}const manager=await User.findOne({_id:req.body.manager,role:'admin',status:'active'});const allowed=[manager?.department,...(manager?.managedDepartments||[])].filter(Boolean).map(String);if(!allowed.length){res.status(400);throw new Error('Selected manager must have a department')}if(req.body.department&&!allowed.includes(String(req.body.department))){res.status(400);throw new Error('Department is not managed by the selected manager')}req.body.department=req.body.department||allowed[0]}const data={...req.body,password:await bcrypt.hash(req.body.password||'Password@123',12)};const x=await User.create(data);await logActivity(req,'create','User',x._id,{email:x.email,role:x.role});const full=await x.populate('department','name code');emitOps(io,full.department,'user:updated',{id:x._id,action:'created'});emitOps(io,full.department,'dashboard:updated');res.status(201).json(cleanUser(full))}));
r.patch('/users/:id',allow('superadmin','admin'),validateBody(schemas.user.partial()),asyncHandler(async(req,res)=>{const target=await User.findById(req.params.id);if(!target){res.status(404);throw new Error('User not found')}if(req.user.role==='admin'&&String(target.manager)!==String(req.user._id)){res.status(403);throw new Error('Outside your team')}delete req.body.password;if(req.user.role==='admin'){if(!req.user.department){res.status(400);throw new Error('Create your department before managing employees')}delete req.body.role;delete req.body.department;req.body.manager=req.user._id}if(req.user.role==='superadmin'&&(req.body.manager||req.body.role==='employee')&&(req.body.role||target.role)==='employee'){if(!req.body.manager){res.status(400);throw new Error('Select a reporting manager for employee')}const manager=await User.findOne({_id:req.body.manager,role:'admin',status:'active'});if(!manager?.department){res.status(400);throw new Error('Selected manager must create a department first')}req.body.department=manager.department}if(req.body.role==='superadmin'&&target.role!=='superadmin'){res.status(409);throw new Error('Only one Super Admin is allowed in the organization')}if(target.role==='superadmin'&&req.body.role&&req.body.role!=='superadmin'){res.status(409);throw new Error('The organization Super Admin role cannot be changed')}const oldDepartment=target.department;Object.assign(target,req.body);await target.save();const full=await target.populate('department','name code');emitOps(io,oldDepartment,'user:updated',{id:target._id,action:'updated'});emitOps(io,full.department,'user:updated',{id:target._id,action:'updated'});emitOps(io,full.department,'dashboard:updated');res.json(cleanUser(full))}));
r.delete('/users/:id',allow('superadmin'),asyncHandler(async(req,res)=>{
  const target=await User.findById(req.params.id).lean();
  if(!target){res.status(404);throw new Error('User not found')}
  if(target.role==='superadmin'){res.status(409);throw new Error('The organization Super Admin cannot be deleted')}

  const team=target.role==='admin'?await User.find({manager:target._id,role:'employee'}).select('_id phone department').lean():[];
  const userIds=[target._id,...team.map(x=>x._id)];
  const rawDepartmentIds=target.role==='admin'?[target.department,...team.map(x=>x.department)].filter(Boolean):[];
  const ownedDepartments=target.role==='admin'?await Department.find({$or:[{head:target._id},{_id:{$in:rawDepartmentIds}}]}).select('_id').lean():[];
  const departmentIds=[...new Set([...rawDepartmentIds.map(String),...ownedDepartments.map(x=>String(x._id))])].map(oid);

  const projectClauses=[{manager:{$in:userIds}},{members:{$in:userIds}}];
  if(departmentIds.length)projectClauses.push({department:{$in:departmentIds}});
  const projects=await Project.find({$or:projectClauses}).select('_id department').lean();
  const projectIds=projects.map(x=>x._id);

  const taskClauses=[{assignedTo:{$in:userIds}},{assignedBy:{$in:userIds}}];
  if(departmentIds.length)taskClauses.push({department:{$in:departmentIds}});
  if(projectIds.length)taskClauses.push({project:{$in:projectIds}});
  const phones=[safePhone(target.phone),...team.map(x=>safePhone(x.phone))].filter(Boolean);
  const recordScope=departmentIds.length?{$or:[{employee:{$in:userIds}},{department:{$in:departmentIds}}]}:{employee:{$in:userIds}};

  const [tasks,dailyWork,attendance,leaves,notifications,resetTokens,otpTokens,activities,templates,projectsDeleted,departmentsDeleted,usersDeleted]=await Promise.all([
    Task.deleteMany({$or:taskClauses}),
    DailyWork.deleteMany(recordScope),
    Attendance.deleteMany(recordScope),
    Leave.deleteMany(recordScope),
    Notification.deleteMany({recipient:{$in:userIds}}),
    ResetToken.deleteMany({user:{$in:userIds}}),
    phones.length?OtpToken.deleteMany({phone:{$in:phones}}):Promise.resolve({deletedCount:0}),
    Activity.deleteMany({actor:{$in:userIds}}),
    DailyTaskTemplate.deleteMany({$or:[{createdBy:{$in:userIds}},{employees:{$in:userIds}},...(departmentIds.length?[{department:{$in:departmentIds}}]:[])]}),
    projectIds.length?Project.deleteMany({_id:{$in:projectIds}}):Promise.resolve({deletedCount:0}),
    departmentIds.length?Department.deleteMany({_id:{$in:departmentIds}}):Promise.resolve({deletedCount:0}),
    User.deleteMany({_id:{$in:userIds}}),
    Project.updateMany({},{$pull:{members:{$in:userIds}}}),
    Project.updateMany({manager:{$in:userIds}},{$unset:{manager:1}}),
    Department.updateMany({head:{$in:userIds}},{$unset:{head:1}}),
    User.updateMany({manager:{$in:userIds}},{$unset:{manager:1}}),
    Task.updateMany({},{$pull:{comments:{author:{$in:userIds}},history:{actor:{$in:userIds}}}}),
    DailyWork.updateMany({reviewedBy:{$in:userIds}},{$unset:{reviewedBy:1}}),
    Leave.updateMany({reviewedBy:{$in:userIds}},{$unset:{reviewedBy:1}})
  ]);

  const emitDepartments=[target.department,...departmentIds].filter(Boolean).map(String);
  for(const department of new Set(emitDepartments)){emitOps(io,department,'user:updated',{ids:userIds,action:'deleted'});emitOps(io,department,'task:updated',{action:'user-deleted',ids:userIds});emitOps(io,department,'dashboard:updated')}
  emitOps(io,null,'dashboard:updated');
  res.json({message:'User and all linked workspace records deleted',deleted:{users:usersDeleted.deletedCount,departments:departmentsDeleted.deletedCount,projects:projectsDeleted.deletedCount,tasks:tasks.deletedCount,dailyWork:dailyWork.deletedCount,attendance:attendance.deletedCount,leaves:leaves.deletedCount,notifications:notifications.deletedCount,resetTokens:resetTokens.deletedCount,otpTokens:otpTokens.deletedCount,activities:activities.deletedCount,dailyTemplates:templates.deletedCount}})
}));
r.get('/projects',asyncHandler(async(req,res)=>{const q=req.user.role==='employee'?{members:req.user._id}:scopeFilter(req);res.json(await Project.find(q).populate('department','name code').populate('manager members','name email').sort('-createdAt'))}));
r.post('/projects',allow('superadmin','admin'),validateBody(schemas.project),asyncHandler(async(req,res)=>{for(const k of ['manager','startDate','endDate'])if(req.body[k]==='')delete req.body[k];if(req.user.role==='admin'){if(!req.user.department){res.status(400);throw new Error('Create your department before adding projects')}req.body.department=req.user.department?._id||req.user.department;req.body.manager=req.user._id}const x=await Project.create(req.body);await logActivity(req,'create','Project',x._id,{name:x.name});emitOps(io,x.department,'project:updated',{id:x._id,action:'created'});emitOps(io,x.department,'dashboard:updated');res.status(201).json(await x.populate('department manager members','name code email'))}));
r.patch('/projects/:id',allow('superadmin','admin'),validateBody(schemas.project.partial()),asyncHandler(async(req,res)=>{for(const k of ['manager','startDate','endDate'])if(req.body[k]==='')delete req.body[k];const x=await Project.findOneAndUpdate({_id:req.params.id,...scopeFilter(req)},req.body,{new:true,runValidators:true});if(!x){res.status(404);throw new Error('Project not found')}emitOps(io,x.department,'project:updated',{id:x._id,action:'updated'});emitOps(io,x.department,'dashboard:updated');res.json(x)}));
r.delete('/projects/:id',allow('superadmin','admin'),asyncHandler(async(req,res)=>{if(await Task.exists({project:req.params.id})){res.status(409);throw new Error('Project has tasks and cannot be deleted')}const x=await Project.findOneAndDelete({_id:req.params.id,...scopeFilter(req)});emitOps(io,x?.department,'project:updated',{id:req.params.id,action:'deleted'});emitOps(io,x?.department,'dashboard:updated');res.json({message:'Project deleted'})}));
r.get('/tasks',asyncHandler(async(req,res)=>{const q=await visibleTaskScope(req);if(req.query.status)q.status=req.query.status;if(req.query.project)q.project=req.query.project;if(req.query.search)q.title=new RegExp(req.query.search,'i');const {page,limit}=parsePage(req);const [items,total]=await Promise.all([Task.find(q).select(req.user.role==='employee'?'-privateEvaluation':'').populate('assignedTo assignedBy','name email avatar').populate('project','name code').populate('department','name code').populate('comments.author','name').sort('-updatedAt').skip((page-1)*limit).limit(limit),Task.countDocuments(q)]);res.json({items,total,page,pages:Math.ceil(total/limit)})}));
r.post('/tasks',allow('superadmin','admin'),validateBody(schemas.task),asyncHandler(async(req,res)=>{if(req.user.role==='admin'){if(!req.user.department){res.status(400);throw new Error('Create your department before assigning tasks')}const teamIds=await teamEmployeeIds(req,User);if(!teamIds.some(id=>String(id)===String(req.body.assignedTo))){res.status(403);throw new Error('Assign tasks only to your team')}req.body.department=req.user.department?._id||req.user.department}const x=await Task.create({...req.body,assignedBy:req.user._id,history:[hist(req,'created','Task assigned')]});await notify(io,x.assignedTo,{type:'task',title:'New task assigned',message:x.title,link:'/tasks'});await logActivity(req,'create','Task',x._id,{title:x.title});emitOps(io,x.department,'task:updated',x);emitOps(io,x.department,'dashboard:updated');res.status(201).json(await x.populate('assignedTo project department','name code'))}));
r.get('/tasks/:id',asyncHandler(async(req,res)=>{const q={_id:req.params.id,...(await visibleTaskScope(req))};const x=await Task.findOne(q).select(req.user.role==='employee'?'-privateEvaluation':'').populate('assignedTo assignedBy','name email').populate('project department','name code').populate('comments.author','name').populate('history.actor','name role');if(!x){res.status(404);throw new Error('Task not found')}res.json(x)}));
r.patch('/tasks/:id',allow('superadmin','admin'),validateBody(schemas.task.partial()),asyncHandler(async(req,res)=>{const scope=req.user.role==='admin'?{assignedTo:{$in:await teamEmployeeIds(req,User)}}:scopeFilter(req);if(req.user.role==='admin'&&req.body.assignedTo&&!scope.assignedTo.$in.some(id=>String(id)===String(req.body.assignedTo))){res.status(403);throw new Error('Assign tasks only to your team')}if(req.user.role==='admin')req.body.department=req.user.department?._id||req.user.department;const x=await Task.findOne({_id:req.params.id,...scope});if(!x){res.status(404);throw new Error('Task not found')}const prev=x.status;Object.assign(x,req.body);if(req.body.status&&req.body.status!==prev)x.history.push(hist(req,'status_changed','Task status changed',prev,req.body.status));else x.history.push(hist(req,'updated','Task details updated'));await x.save();io.to(String(x.assignedTo)).emit('task:updated',x);emitOps(io,x.department,'task:updated',x);emitOps(io,x.department,'dashboard:updated');res.json(x)}));
r.patch('/tasks/:id/progress',validateBody(schemas.taskProgress),asyncHandler(async(req,res)=>{const x=await Task.findOne({_id:req.params.id,assignedTo:req.user._id});if(!x){res.status(404);throw new Error('Task not found')}const prev=Number(x.progress)||0;const next=Math.max(0,Math.min(100,Number(req.body.progress)));if(next===prev)return res.json(x);x.progress=next;if(x.status==='pending')x.status='in-progress';x.history.push(hist(req,'progress_updated','Progress updated',prev,x.progress));await x.save();emitOps(io,x.department,'task:updated',x);emitOps(io,x.department,'dashboard:updated');res.json(x)}));
r.post('/tasks/:id/comments',validateBody(schemas.taskComment),asyncHandler(async(req,res)=>{const q={_id:req.params.id,...(await visibleTaskScope(req))};const x=await Task.findOne(q);if(!x){res.status(404);throw new Error('Task not found')}x.comments.push({author:req.user._id,text:req.body.text});x.history.push(hist(req,'commented','Comment added'));await x.save();io.to(String(x.assignedTo)).emit('task:updated',x);emitOps(io,x.department,'task:updated',x);res.status(201).json(x.comments.at(-1))}));
r.post('/tasks/:id/attachments',upload.single('file'),asyncHandler(async(req,res)=>{const q={_id:req.params.id,...(await visibleTaskScope(req))};const x=await Task.findOne(q);if(!x){res.status(404);throw new Error('Task not found')}if(!req.file){res.status(400);throw new Error('File is required')}let url;if(process.env.UPLOAD_PROVIDER==='cloudinary'){const result=await uploadAttachment(req.file);url=result.secure_url}else{const filename=`${crypto.randomBytes(16).toString('hex')}${path.extname(req.file.originalname)}`;fs.writeFileSync(path.join(uploadDir,filename),req.file.buffer);url='/uploads/'+filename}const a={name:req.file.originalname,url,size:req.file.size,mime:req.file.mimetype,uploadedBy:req.user._id};x.attachments.push(a);x.history.push(hist(req,'file_uploaded','Attachment uploaded'));await x.save();io.to(String(x.assignedTo)).emit('task:updated',x);emitOps(io,x.department,'task:updated',x);res.status(201).json(x.attachments.at(-1))}));
r.post('/tasks/:id/submit',allow('employee'),validateBody(schemas.taskSubmit),asyncHandler(async(req,res)=>{const x=await Task.findOne({_id:req.params.id,assignedTo:req.user._id});if(!x){res.status(404);throw new Error('Task not found')}const files=x.attachments||[],requirements=x.completionRequirements||[],matches={photo:files.some(f=>String(f.mime||'').startsWith('image/')),screenshot:files.some(f=>String(f.mime||'').startsWith('image/')),document:files.some(f=>/pdf|word|text/.test(String(f.mime||''))),excel:files.some(f=>/excel|spreadsheet|csv/.test(String(f.mime||''))),invoice:files.some(f=>/invoice|bill/i.test(f.name||'')),['customer-confirmation']:files.some(f=>/confirmation|customer/i.test(f.name||'')),remark:Boolean(req.body.note?.trim())};const missing=requirements.filter(type=>!matches[type]);if(missing.length){res.status(400);throw new Error(`Completion requires: ${missing.join(', ')}`)}const prev=x.status;x.status='completed';x.progress=100;x.submissionNote=req.body.note;x.completedAt=new Date();x.history.push(hist(req,'completed','Task marked completed',prev,'completed'));await x.save();if(String(x.assignedBy)!==String(req.user._id))await notify(io,x.assignedBy,{type:'task-completed',title:'Task completed',message:`${req.user.name} completed ${x.title}`,link:'/tasks'});emitOps(io,x.department,'task:updated',x);emitOps(io,x.department,'dashboard:updated');res.json({message:'Task marked completed',task:x})}));
r.post('/tasks/:id/review',allow('superadmin','admin'),validateBody(schemas.taskReview),asyncHandler(async(req,res)=>{const scope=req.user.role==='admin'?{assignedTo:{$in:await teamEmployeeIds(req,User)}}:scopeFilter(req);const x=await Task.findOne({_id:req.params.id,...scope});if(!x){res.status(404);throw new Error('Task not found')}const prev=x.status;x.status=req.body.decision;x.reviewNote=req.body.note||'';if(req.body.decision==='completed')x.privateEvaluation={points:Number(req.body.points||0),quality:Number(req.body.quality||0),rating:Number(req.body.rating||0)};x.history.push(hist(req,'status_changed',`Task marked ${req.body.decision}`,prev,req.body.decision));await x.save();await notify(io,x.assignedTo,{type:'task-status',title:'Task status updated',message:`${x.title}: ${x.status}`,link:'/tasks'});io.to(String(x.assignedTo)).emit('task:updated',x);emitOps(io,x.department,'task:updated',x);emitOps(io,x.department,'dashboard:updated');res.json(x)}));
r.delete('/tasks/:id',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const scope=req.user.role==='admin'?{assignedTo:{$in:await teamEmployeeIds(req,User)}}:scopeFilter(req);const x=await Task.findOneAndDelete({_id:req.params.id,...scope});if(x)io.to(String(x.assignedTo)).emit('task:updated',{id:x._id,action:'deleted'});emitOps(io,x?.department,'task:updated',{id:req.params.id,action:'deleted'});emitOps(io,x?.department,'dashboard:updated');res.json({message:'Task deleted'})}));

// Daily fixed work updates: one record per employee per calendar day.
r.get('/daily-work/today',allow('employee'),asyncHandler(async(req,res)=>{const date=new Date().toISOString().slice(0,10);let row=await DailyWork.findOne({employee:req.user._id,date}).populate('reviewedBy','name');if(!row)row=await DailyWork.create({employee:req.user._id,department:req.user.department?._id||req.user.department,date});res.json(row)}));
r.patch('/daily-work/today',allow('employee'),validateBody(schemas.dailyWork),asyncHandler(async(req,res)=>{const date=new Date().toISOString().slice(0,10);const allowed={};for(const k of ['progress','workSummary','blockers','tomorrowPlan'])if(req.body[k]!==undefined)allowed[k]=req.body[k];allowed.status=Number(allowed.progress||0)>0?'in-progress':'pending';const row=await DailyWork.findOneAndUpdate({employee:req.user._id,date},{$set:allowed,$setOnInsert:{department:req.user.department?._id||req.user.department}},{new:true,upsert:true,runValidators:true});emitOps(io,row.department,'daily-work:updated',row);emitOps(io,row.department,'dashboard:updated');res.json(row)}));
r.patch('/daily-work/today/generated-tasks/:taskId',allow('employee'),asyncHandler(async(req,res)=>{const date=new Date().toISOString().slice(0,10),row=await DailyWork.findOne({employee:req.user._id,date});if(!row){res.status(404);throw new Error('Daily work not found')}if(['submitted','approved'].includes(row.status)){res.status(400);throw new Error('Submitted daily work cannot be changed')}const task=row.generatedTasks.id(req.params.taskId);if(!task){res.status(404);throw new Error('Fixed task not found')}task.done=Boolean(req.body.done);if(row.generatedTasks.length){row.progress=Math.round((row.generatedTasks.filter(x=>x.done).length/row.generatedTasks.length)*100);row.status=row.progress?'in-progress':'pending'}await row.save();emitOps(io,row.department,'daily-work:updated',row);emitOps(io,row.department,'dashboard:updated');res.json(row)}));
r.post('/daily-work/today/submit',allow('employee'),validateBody(schemas.dailySubmit),asyncHandler(async(req,res)=>{const date=new Date().toISOString().slice(0,10);const row=await DailyWork.findOneAndUpdate({employee:req.user._id,date},{$set:{status:'submitted',progress:100,workSummary:req.body.workSummary,blockers:req.body.blockers||'',tomorrowPlan:req.body.tomorrowPlan||'',submissionNote:req.body.submissionNote||'',submittedAt:new Date()},$setOnInsert:{department:req.user.department?._id||req.user.department}},{new:true,upsert:true,runValidators:true});emitOps(io,row.department,'daily-work:submitted',row);emitOps(io,row.department,'dashboard:updated');await notify(io,req.user._id,{type:'daily',title:'Daily update submitted',message:'Your daily work update was submitted successfully.',link:'/daily-work'});if(req.user.manager)await notify(io,req.user.manager,{type:'daily-submitted',title:'Daily update ready for review',message:`${req.user.name} submitted today's daily update.`,link:'/daily-work'});res.json(row)}));
r.get('/daily-work',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const q=await managerEmployeeScope(req);if(req.query.date)q.date=req.query.date;if(req.query.status)q.status=req.query.status;if(req.query.employee)q.employee=req.query.employee;const rows=await DailyWork.find(q).populate('employee','name email designation').populate('department','name code').populate('reviewedBy','name').sort('-date -updatedAt').limit(300);res.json(rows)}));
r.post('/daily-work/:id/review',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const scope=await managerEmployeeScope(req);const row=await DailyWork.findOne({_id:req.params.id,...scope});if(!row){res.status(404);throw new Error('Daily update not found')}if(!['approved','rework'].includes(req.body.decision)){res.status(400);throw new Error('Decision must be approved or rework')}row.status=req.body.decision;row.reviewNote=req.body.reviewNote||'';row.reviewedAt=new Date();row.reviewedBy=req.user._id;await row.save();await notify(io,row.employee,{type:'daily-review',title:req.body.decision==='approved'?'Daily update approved':'Daily update needs changes',message:row.reviewNote||row.date,link:'/daily-work'});io.to(String(row.employee)).emit('daily-work:updated',row);emitOps(io,row.department,'daily-work:updated',row);emitOps(io,row.department,'dashboard:updated');res.json(row)}));

r.get('/notifications',asyncHandler(async(req,res)=>res.json(await Notification.find({recipient:req.user._id}).sort('-createdAt').limit(50))));
r.patch('/notifications/:id/read',asyncHandler(async(req,res)=>{const x=await Notification.findOneAndUpdate({_id:req.params.id,recipient:req.user._id},{read:true},{new:true});io.to(String(req.user._id)).emit('notification:read',x);res.json(x)}));
r.patch('/notifications/read-all',asyncHandler(async(req,res)=>{await Notification.updateMany({recipient:req.user._id,read:false},{read:true});io.to(String(req.user._id)).emit('notification:read',{all:true});res.json({message:'All read'})}));
r.get('/activities',allow('superadmin','admin'),asyncHandler(async(req,res)=>res.json(await Activity.find(req.user.role==='superadmin'?{}:{actor:req.user._id}).populate('actor','name email').sort('-createdAt').limit(100))));
r.get('/reports/summary',allow('superadmin','admin'),asyncHandler(async(req,res)=>{const q=req.user.role==='admin'?{assignedTo:{$in:await teamEmployeeIds(req,User)}}:{...scopeFilter(req)};if(req.user.role==='superadmin'&&req.query.department)q.department=oid(req.query.department);if(req.query.project)q.project=oid(req.query.project);if(req.query.status)q.status=req.query.status;if(req.query.from||req.query.to)q.dueDate={...(req.query.from?{$gte:new Date(req.query.from)}:{}),...(req.query.to?{$lte:new Date(req.query.to+'T23:59:59')}:{})};const byStatus=await Task.aggregate([{$match:q},{$group:{_id:'$status',count:{$sum:1}}}]);const byPriority=await Task.aggregate([{$match:q},{$group:{_id:'$priority',count:{$sum:1}}}]);const overdue=await Task.countDocuments({...q,dueDate:{$lt:new Date()},status:{$nin:['completed','not-applicable']}});const productivity=await Task.aggregate([{$match:{...q,status:'completed'}},{$group:{_id:'$assignedTo',completed:{$sum:1},avgRating:{$avg:'$privateEvaluation.rating'}}},{$sort:{completed:-1}},{$limit:10},{$lookup:{from:'users',localField:'_id',foreignField:'_id',as:'user'}},{$unwind:'$user'},{$project:{name:'$user.name',completed:1,avgRating:{$round:['$avgRating',1]}}}]);res.json({byStatus,byPriority,overdue,productivity,filters:{department:req.query.department||'',project:req.query.project||'',status:req.query.status||'',from:req.query.from||'',to:req.query.to||''}})}));
r.get('/settings',allow('superadmin'),asyncHandler(async(req,res)=>{const rows=await Setting.find();res.json(Object.fromEntries(rows.map(x=>[x.key,x.value])))}));
r.put('/settings',allow('superadmin'),validateBody(schemas.settings),asyncHandler(async(req,res)=>{await Promise.all(Object.entries(req.body).map(([key,value])=>Setting.findOneAndUpdate({key},{value},{upsert:true,new:true})));emitOps(io,null,'settings:updated');res.json({message:'Settings saved'})}));
return r}
